name: Deploy SAM Application

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install AWS CLI and SAM CLI
        run: |
          pip install awscli aws-sam-cli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Build with SAM
        run: |
          cd ./sam_lambda/app-74
          sam build

      - name: Deploy with SAM
        run: |
          cd ./sam_lambda/app-74
          
          # Allow the deploy command to run without stopping on failure
          set +e
          
          # Capture output and error code
          DEPLOY_OUTPUT=$(sam deploy --no-confirm-changeset --stack-name img-generator-sam --capabilities CAPABILITY_IAM 2>&1)
          DEPLOY_EXIT_CODE=$?
          
          # Re-enable stopping on failure
          set -e
          
          # Print the output for logging
          echo "$DEPLOY_OUTPUT"
          
          # Check the exit code and handle accordingly
          if [[ $DEPLOY_EXIT_CODE -eq 0 ]]; then
            echo "Deploy successful"
          elif echo "$DEPLOY_OUTPUT" | grep -q "No changes to deploy"; then
            echo "No changes to deploy"
            exit 0
          else
            echo "SAM Deploy failed with an unexpected error"
            exit $DEPLOY_EXIT_CODE
          fi
