name: Deploy SAM Application

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install AWS CLI
        run: |
          pip install awscli aws-sam-cli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Build with SAM
        run: |
          cd ./sam_lambda/app-74
          sam build

      - name: Deploy with SAM
        run: |
          cd ./sam_lambda/app-74
          set +e
          sam deploy --no-confirm-changeset --stack-name img-generator-sam --capabilities CAPABILITY_IAM
          DEPLOY_EXIT_CODE=$?
          set -e
          if [ $DEPLOY_EXIT_CODE -eq 0 ]; then
            echo "Deploy successful"
          elif [ $DEPLOY_EXIT_CODE -eq 1 ] && grep -q "No changes to deploy" .aws-sam/log/deploy.log; then
            echo "No changes to deploy"
          else
            echo "SAM Deploy failed"
            exit $DEPLOY_EXIT_CODE
          fi
